- examples_test.go
Resolved loc predicate error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgo/10)
> Updated examples_test.go

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgo/21)
> Added doc for how to set metadata headers

- example_set_object_test.go
- examples_test.go
- setup-cluster.sh
- test.sh
Tested with "go test"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgo/22)
> Using external cluster for testing

- example_set_object_test.go
- examples_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgo/38)
> Fix obsolete field name in comments

- example_get_schema_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgo/43)
> Example of getting schema info in JSON response

- examples_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgo/57)
> Add example about login method in example.

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgo/59)
> Add new section on how to use RDF for mutations.

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgo/49)
> Update docs with info on read-only transactions.

- examples_test.go
- txn.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgo/64)
> Fixing the Discard function by actually discarding an uncommitted txn

- client.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgo/71)
> client: fixed Value_DefaultVal composite literal uses unkeyed fields

- protos/api/api.pb.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgo/76)
> Regenerate proto files

- client.go
- doc.go
- example_set_object_test.go
- examples_test.go
- txn.go
- y/y.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgo/79)
> Fix tests and golint warnings

- examples_test.go
- protos/api.proto
- protos/api/api.pb.go
- txn.go
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgo/77)
> breaking change: Merge Mutate and Query endpoint into Query endpoint

- README.md
- upsert_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgo/84)
> Add test and docs for Upsert

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgo/88)
> Update docs for Upsert

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgo/89)
> Minor change in docs

- example_set_object_test.go
- examples_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgo/90)
> Indent the output of test

- acl_test.go
- errors_test.go
- typesystem_test.go
- upsert_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgo/92)
> Add tests for ACLs, TypeSystem, Errors

- example_get_schema_test.go
related to https://github.com/dgraph-io/dgraph/pull/4107
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgo/106)
> Login before running schema queries

- txn.go
- txn_test.go
Fixes #105
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgo/109)
> Do not discard the transaction if it's not mutation

- acl_test.go
- example_set_object_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgo/113)
> Fix ACLs test

- acl_test.go
- examples_test.go
Related to
https://github.com/dgraph-io/dgraph/commit/1a0f2c998dedc10d270c71b05bd3a9c9b272b7b6
https://github.com/dgraph-io/dgraph/pull/4267
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgo/115)
> Fix facets test

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgo/116)
> Adds "Supported Versions" section

- README.md
- acl_test.go
- errors_test.go
- example_get_schema_test.go
- example_set_object_test.go
- examples_test.go
- type_system_test.go
- upsert_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgo/117)
> Fix tests due to indexing in background

- README.md
- acl_test.go
- errors_test.go
- example_get_schema_test.go
- example_set_object_test.go
- examples_test.go
- type_system_test.go
- upsert_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgo/119)
> Add docs for background indexing

- RELEASE.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgo/121)
> Add steps to release dgo client

- RELEASE.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgo/122)
> Minor change in release docs

- .github/ISSUE_TEMPLATE
- .github/workflows/main.yml
- README.md
Add Github Action script for auto close of issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgo/131)
> Enabled  Issue Auto-close

- test.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgo/140)
> fix(test): fixing test cases for dgo client

- txn.go
There was a typo in mergeContext.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgo/144)
> fix(txn): fix the typo in mergeContext

- client.go
- txn.go
These APIs are needed by https://github.com/dgraph-io/dgraph/pull/7568
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgo/145)
> feat(api): Add GetJwt and Relogin APIs

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dgraph-io/dgo/154)
> docs: Switched mentions of GraphQL+- to DQL

- README.md
Update table in readme for release v230.
> chore(release): update readme for supported releases
